name: Run PSPSScriptAnalyzer on PowerShell Scripts

on:
  push:

jobs:
  PSScriptAnalyzer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run PSScriptAnalyzer on PowerShell Scripts
        shell: pwsh
        run: |
          Invoke-ScriptAnalyzer -Path ./azure-test/ -Recurse -Severity Error -EnableExit
